### PR TITLE
Create Vec based on Managed Memory

### PR DESCRIPTION
**Pull request by kpp**
I named it MVec (M stands for Managed wheres U stands for Uniformed (I guess so))

### CODE REVIEW

**Comment by termoshtt** [comment]
Manged memory reserved by `cudaMalloc` cannot be accessed from host code since it is allocated on the device. I agree to create an interface for managed memory, but we should not implement `Deref`and `Index` for it. I think the approach by thrust, i.e. creating `host_vector` and `device_vector` will be better. Your `MVec` seems to corresponds to `device_vector`. Could you create memcpy wrapper from `Vec` to `MVec`?

**Comment by kpp** [comment]
Sure! I am working on it.

**Comment by kpp** [comment]
```
---- uvec::tests::uvec_new stdout ----
	thread 'uvec::tests::uvec_new' panicked at 'called `Result::unwrap()` on an `Err` value: cudaRuntimeError(InsufficientDriver)', libcore/result.rs:945:5
```

seems like you did not set up your CI and build env correctly. I can write the code but I can't check it locally.

**Comment by termoshtt** [comment]
> seems like you did not set up your CI and build env correctly. I can write the code but I can't check it locally.

CI with GPU is not running currently #9

**Comment by kpp** [comment]
> Could you create memcpy wrapper from Vec to MVec?

done

**Comment by termoshtt** [comment]
Sorry for later replay. I will merge it after I confirm it works on my env.

**Comment by termoshtt** [comment]
Fix host vector init, and it works well. Thanks :)

**Pull request merged**
